{% set name = "qsymm" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3920e49207f597cb41706b97a15e832c342ebbbfc3d0e20207cd7318ad205221

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.7
    - pytest-runner
  run:
    - numpy >=1.16.2
    - python >=3.7
    - scipy >=1.1
    - sympy >=1.3
    - tinyarray >=1.2.2

test:
  requires:
    - pytest
    - setuptools
  imports:
    - qsymm
    - qsymm.tests
  commands:
    - py.test --pyargs qsymm

about:
  home: https://gitlab.kwant-project.org/qt/qsymm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Symmetry finder and symmetric Hamiltonian generator

extra:
  recipe-maintainers:
    - jbweston
    - dvarjas
    - torosdahl
    - akhmerov
