{% set name = "qsymm" %}
{% set version = "1.2.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9af92a30c3f72883c744d4717e4ec30c8b48121e208c10553e8e0e428fe43bbc

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.5
    - pytest-runner
  run:
    - numpy >=1.13
    - python >=3.5
    - scipy >=0.19
    - sympy >=1.1
    - tinyarray

test:
  requires:
    - pytest
  imports:
    - qsymm
    - qsymm.tests
  commands:
    - py.test --pyargs qsymm

about:
  home: https://gitlab.kwant-project.org/qt/qsymm
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Symmetry finder and symmetric Hamiltonian generator

extra:
  recipe-maintainers:
    - jbweston
    - dvarjas
    - torosdahl
    - akhmerov
